FROM microsoft/windowsservercore
LABEL maintainer='Travis Plunk <github@ez13.net>'
LABEL readme.md="https://github.com/TravisEz13/docker/blob/master/microsoft/windowsservercore/git_and_nuget/readme.md"
LABEL description="This Dockerfile for Windows Server Core with git and NuGet installed via chocolatey.  See readme on docker hub for licensing."

SHELL ["powershell"]
COPY installcmake.ps1 /
COPY cleanupchocolatey.ps1 /
RUN Write-Verbose Installing.Chocolatey... -Verbose; \
    Install-PackageProvider -Name Chocolatey -Force; \
    Write-Verbose Installing.git... -Verbose; \
    Install-Package -Name git -ProviderName Chocolatey -Force; \
    Write-Verbose Installing.nuget... -Verbose; \
    Install-Package -Name nuget.commandline -ProviderName Chocolatey -Force; \
    ./cleanupchocolatey.ps1
