FROM microsoft/windowsservercore
LABEL maintainer='Travis Plunk <github@ez13.net>'
LABEL readme.md="https://github.com/TravisEz13/docker/blob/master/microsoft/windowsservercore/git_and_nuget/readme.md"
LABEL description="This Dockerfile for Windows Server Core with git and NuGet installed via chocolatey.  See readme on docker hub for licensing."

SHELL ["powershell"]
COPY installusingchocolatey.ps1 /
RUN ./installusingchocolatey.ps1 -PackageName git -Executable git.exe; \
    ./installusingchocolatey.ps1 -PackageName nuget.commandline -Executable nuget.exe; \
    ./installusingchocolatey.ps1 -PackageName cmake.install -Executable cmake.exe -Cleanup
