FROM microsoft/windowsservercore
LABEL maintainer='Travis Plunk <github@ez13.net>'
LABEL readme.md="https://github.com/TravisEz13/docker/blob/master/microsoft/windowsservercore/git_and_nuget/readme.md"
LABEL description="This Dockerfile for Windows Server Core with git and NuGet installed via chocolatey.  See readme on docker hub for licensing."

SHELL ["powershell"]
RUN Invoke-WebRequest https://chocolatey.org/install.ps1 -UseBasicParsing | Invoke-Expression
RUN choco install -y git; \
    Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force; \
    choco install -y nuget.commandline
